name: build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IN_FILE: opus-iso-binding.md
      OUT_FILE_NAME: opus-iso-binding
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: sudo gem install kramdown
      - run: kramdown --template build/html-template ${{ env.IN_FILE }} > ${{ env.OUT_FILE_NAME }}.html
      - run: |
          docker run --security-opt seccomp=unconfined \
          --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf --no-cache \
          ${{ env.OUT_FILE_NAME }}.html ${{ env.OUT_FILE_NAME }}.pdf
